version: "3.3"
services:
  glass:
    image: docker.tradingapps.com:443/ta-qa-rhel7:20181011150454
    ports:
      - :80
    networks:
      - default
    volumes:
      - "working:/working"
      - "glass:/home/glass"
    deploy:
      resources:
        reservations:
          memory: 3G
      placement:
        constraints:
          - node.labels.qa == true
      restart_policy:
        condition: none
    environment:
      JOB_NAME: ${JOB_NAME}
      GLASSES: ${GLASSES}
      DEPLOY_EXTRA_ARGS: -force -qa-mail -qa-mail-ssl -single-glass -minimal-glass-logging -glass-dbs "mysql:host=db:database=GLASS"
      STAY_ALIVE: "TRUE"
      DEBUG_CONTAINER: "TRUE"
      TARGET_HOST_FQDN: glass
      MYSQL_ROOT_PASSWORD: ta
      DB_TYPE: mysql
      GLASS_MYSQL_HOST: db
      GLASS_MYSQL_PORT: 3306
      GLASS_MYSQL_DB_NAME: GLASS
  db:
    image: mariadb:latest
    ports:
      - :3306
    networks:
      - default
    volumes:
      - "mysql:/var/lib/mysql"
    deploy:
      resources:
        reservations:
          memory: 1G
      placement:
        constraints:
          - node.labels.qa == true
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ta

  adminer:
    image: adminer
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.qa == true
    ports:
      - :8080

volumes:
  glass:
  working:
  mysql:
