version: "3.3"
services:
  glass:
    image: docker.tradingapps.com:443/ta-qa-rhel7:${DOCKER_TA_QA_RHEL7_IMAGE_TAG}
    ports:
      - :80
    networks:
      - default
    volumes:
      - "working:/working"
      - "glass:/home/glass"
    deploy:
      resources:
        reservations:
          memory: 2G
      placement:
        constraints:
          - node.labels.qa == true
      restart_policy:
        condition: none
    environment:
      JENKINS_JOB_NAME: ${JENKINS_JOB_NAME}
      GLASSES: ${GLASSES}
      DEPLOY_EXTRA_ARGS: -force -qa-mail-ssl -single-glass -minimal-glass-logging -glass-dbs "mysql:host=db:database=GLASS"
      STAY_ALIVE: "TRUE"
      DEBUG_CONTAINER: "FALSE"
      TARGET_HOST_FQDN: glass
      MYSQL_ROOT_PASSWORD: ta
      DB_TYPE: mysql
      GLASS_MYSQL_HOST: db
      GLASS_MYSQL_PORT: 3306
      GLASS_MYSQL_DB_NAME: GLASS
      SUPPORT_FILES_SMB_PATH: //mksvr113.tradingapps.com/Files
      SVN_HOST: mksvr115.tradingapps.com:3692
      SVN_USER: jenkins
      SVN_PASSWORD: 01dec18
      JENKINS_HOST: "${JENKINS_HOSTNAME}"
      JENKINS_PORT: 8080
      JENKINS_USER: jenkins
      JENKINS_PASSWORD: jenkins

  db:
    image: mariadb:latest
    ports:
      - :3306
    networks:
      - default
    volumes:
      - "mysql:/var/lib/mysql"
    deploy:
      resources:
        reservations:
          memory: 1G
      placement:
        constraints:
          - node.labels.qa == true
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ta

  adminer:
    image: adminer
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.qa == true
    ports:
      - :8080

volumes:
  glass:
  working:
  mysql:
